config/routes.rb
Rails.application.routes.draw do
  root 'todos#index'
  resources :todos

end

app/models/todo.rb
class Todo < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  def index
    @todos = Todo.all
  end

  def create
    @todo = Todo.create(todo_params)

    respond_to do |format|
      format.html { redirect_to root_path }
      format.js { }
    end
  end

  def destroy
    @todo = Todo.find(params[:id])
    @todo.destroy

    respond_to do |format|
      format.html { redirect_to root_path }
      format.js { }
    end
  end

  private
    def todo_params
      params.require(:todo).permit(:description, :priority)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TodoApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/todos/_todo.html.erb
<li id="<%= todo.id %>">
  <%= todo.description %><br>
  <strong>priority: </strong><%= todo.priority %><br>
  <%= link_to "done", todo_path(todo), method: 'delete', remote: true %>
</li>

app/views/todos/create.js.erb
$('ul').append("<%= j render partial: 'todo', locals: {todo: @todo} %>");

app/views/todos/destroy.js.erb
$("li#<%= @todo.id %>").slideUp();

app/views/todos/index.html.erb
<h1>My Todos</h1>

<%= form_for Todo.new, remote: true do |f| %>
  <div class="form-group">
    <%= f.text_field :description, placeholder:
    "what needs doing?" %>
  </div>

  <div class="form-group">
    <%= f.text_field :priority, placeholder: "priority level" %>
  </div>

  <div class="form-group">
  <%= f.submit %>
  </div>
<% end %>

<ul>
  <%= render @todos %>
</ul>